// A collection of base64 encoded sound effects for different UI themes.
// Sounds from mixkit.co and pixabay.com - short and suitable for UI.
// Encoded to base64. These are placeholders representing real sounds.

export const sounds = {
  hacker: {
    click: 'data:audio/wav;base64,UklGRigCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQCAAD+f/4A/v/+APz//gD8//4A/f/+APz//gD9//4A/P/+AP3//gD9//4A/P/+AP3//gD9//4A/P/+AA==',
    complete: 'data:audio/wav;base64,UklGRjACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAgAAAEAwEBAgAFAAMABQACAAICAgADAAMABAACAAQAAgADAAQAAgADAAQAAgADAAQAAwADAAE=',
    achievement: 'data:audio/wav;base64,UklGRkgCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSgCAAAFBgcJDA0ODxITFBYZGhscHR8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0A=',
    add: 'data:audio/wav;base64,UklGRjQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSwCAAD0/v/8/v7+/v79/v78/v3+/v39/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v4=',
    timer: 'data:audio/wav;base64,UklGRigCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQCAACgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoA==',
    error: 'data:audio/wav;base64,UklGRkgCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSgCAACgYGBaWFhSUlBMTExHR0dAQEA7OzsxMTAnJycbGxsaGhoaGhoaGhoaGhoaGhoaGho=',
    toggleOn: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAACAgIA=',
    toggleOff: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAIBAgA==',
    levelUp: 'data:audio/wav;base64,UklGRlQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YEgCAAAABg0WHSAlLjE5P0ZPU1tdb3uEj5uop7O9wsjM1Nve5Ovt8vX5/f7//v79/f39/f39/f0=',
    cache_drop: 'data:audio/wav;base64,UklGRkgCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSgCAAAFBgcJDA0ODxITFBYZGhscHR8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0A=',
    cache_open: 'data:audio/wav;base64,UklGRlQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YEgCAAAABg0WHSAlLjE5P0ZPU1tdb3uEj5uop7O9wsjM1Nve5Ovt8vX5/f7//v79/f39/f39/f0=',
  },
  zen: { 
    click: 'data:audio/wav;base64,UklGRiACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAYAACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA=',
    complete: 'data:audio/wav;base64,UklGRigCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
    achievement: 'data:audio/wav;base64,UklGRjACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAgAAAEAwEBAgAFAAMABQACAAICAgADAAMABAACAAQAAgADAAQAAgADAAQAAgADAAQAAwADAAE=',
    add: 'data:audio/wav;base64,UklGRjQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSwCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
    timer: 'data:audio/wav;base64,UklGRigCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQCAACQkJCUlJSYmJienp6ioqKlpaWmpqaoqKipqamoqKipqak=',
    error: 'data:audio/wav;base64,UklGRkgCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSgCAABvb2lpaGRgXl1bVVNRTk1JR0FAPDo2NDAyLisnJSUjISAcFhQRDg0JBgIBAAAA',
    toggleOn: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAEBAQA==',
    toggleOff: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAECAgA==',
    levelUp: 'data:audio/wav;base64,UklGRlQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YEgCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
    cache_drop: 'data:audio/wav;base64,UklGRjACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAgAAAEAwEBAgAFAAMABQACAAICAgADAAMABAACAAQAAgADAAQAAgADAAQAAgADAAQAAwADAAE=',
    cache_open: 'data:audio/wav;base64,UklGRlQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YEgCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
  },
  stealth: {
    click: 'data:audio/wav;base64,UklGRiACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAYAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEA==',
    complete: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAACAIA==',
    achievement: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAAgICAAAAA==',
    add: 'data:audio/wav;base64,UklGRiACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAYAAAAAAAIAAwAFAAkACQAJAAgABgADAAEAAQABAAAAAAA=',
    timer: 'data:audio/wav;base64,UklGRigCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQCAACAgIAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==',
    error: 'data:audio/wav;base64,UklGRiACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAYAAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==',
    toggleOn: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACACAAIA==',
    toggleOff: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACACBAQA==',
    levelUp: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAAgICAAAAA==',
    cache_drop: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAAgICAAAAA==',
    cache_open: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAAgICAAAAA==',
  },
  fantasy: {
    click: 'data:audio/wav;base64,UklGRiACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAYAAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==',
    complete: 'data:audio/wav;base64,UklGRjACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAgAAAICBAYHCAgKCw0ODxESExQVFhgaHB0fICEiIyQlJicnKCkq=',
    achievement: 'data:audio/wav;base64,UklGRjACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAgAAAEAwEBAgAFAAMABQACAAICAgADAAMABAACAAQAAgADAAQAAgADAAQAAgADAAQAAwADAAE=',
    add: 'data:audio/wav;base64,UklGRjQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSwCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
    timer: 'data:audio/wav;base64,UklGRigCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQCAACAgIAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==',
    error: 'data:audio/wav;base64,UklGRkgCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSgCAABvb2lpaGRgXl1bVVNRTk1JR0FAPDo2NDAyLisnJSUjISAcFhQRDg0JBgIBAAAA',
    toggleOn: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAEBAQA==',
    toggleOff: 'data:audio/wav;base64,UklGRiQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQACAECAgA==',
    levelUp: 'data:audio/wav;base64,UklGRlQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YEgCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
    cache_drop: 'data:audio/wav;base64,UklGRjACAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YSAgAAAEAwEBAgAFAAMABQACAAICAgADAAMABAACAAQAAgADAAQAAgADAAQAAgADAAQAAwADAAE=',
    cache_open: 'data:audio/wav;base64,UklGRlQCAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YEgCAAC/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v78=',
  },
};

export type SoundType = keyof typeof sounds.hacker;